apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot_app
  template:
    metadata:
      labels:
        app: springboot_app
    spec:
      containers:
      - name: springboot
        image: pyronaid/custom_springboot_app:0.0.1
        ports:
        - containerPort: 7071
        env:
          - name: mongo-url
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo-url
          - name: mongo-springboot-db
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo-springboot-db
          - name: mongo-user
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-user
          - name: mongo-password
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service-ext
spec:
  type: LoadBalancer
  selector:
    app: springboot_app
  ports:
    - protocol: TCP
      port: 7071
      targetPort: 7071
      nodePort: 30071