apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot_app
  template:
    metadata:
      labels:
        app: springboot_app
    spec:
      containers:
      - name: springboot
        image: pyronaid/custom_springboot_app:latest
        ports:
        - containerPort: 7071
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service-ext
spec:
  type: NodePort
  selector:
    app: springboot_app
  ports:
    - protocol: TCP
      port: 7071
      targetPort: 7071
      nodePort: 30071